version: "3.9"

services:
  mysql_assignment_local:
    image: mysql:5.7.43
    platform: linux/amd64
    container_name: mysql_assignment_local
    environment:
      - LANG=C.UTF-8
      - MYSQL_DATABASE=assignmentdb
      - MYSQL_USER=tester
      - MYSQL_PASSWORD=tester
      - MYSQL_ROOT_PASSWORD=root_password
    command:
      - --ssl=0
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.volumes:/var/lib/mysql --user 1000
      - ./config/db:/docker-entrypoint-initdb.d
      - ./config:/etc/mysql/conf.d
    ports:
      - "3308:3306"
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"